// <auto-generated />
using System;
using CoffeeBook.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoffeeBook.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211118162637_DataSeeding")]
    partial class DataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("CoffeeBook.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin123",
                            RoleId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("CoffeeBook.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Đang chờ thanh toán");

                    b.Property<long>("TotalPrice")
                        .HasColumnType("bigint");

                    b.Property<int>("Validated")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bill");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Status = "Paid",
                            TotalPrice = 100000L,
                            Validated = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 1,
                            Status = "Pending",
                            TotalPrice = 120000L,
                            Validated = 0
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 1,
                            Status = "Active",
                            TotalPrice = 50000L,
                            Validated = 1
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 1,
                            Status = "Pending",
                            TotalPrice = 80000L,
                            Validated = 1
                        });
                });

            modelBuilder.Entity("CoffeeBook.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<string>("Avata")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("Username", "Email", "Phone")
                        .IsUnique();

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "167/19 Đặng Thùy Trâm",
                            Avata = "nhat.png",
                            City = "Hồ Chí Minh",
                            Country = "Việt Nam",
                            Email = "khachhang1@gmail.com",
                            Gender = 1,
                            Name = "Võ Hoàng Nhật",
                            Password = "khachhang1",
                            Phone = "0942400722",
                            Username = "khachhang1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "167/19 Đặng Thùy Trâm",
                            Avata = "qhuy.png",
                            City = "Hồ Chí Minh",
                            Country = "Việt Nam",
                            Email = "khachhang2@gmail.com",
                            Gender = 1,
                            Name = "Bùi Quốc Huy",
                            Password = "khachhang2",
                            Phone = "0942400723",
                            Username = "khachhang2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "167/19 Đặng Thùy Trâm",
                            Avata = "hoang.png",
                            City = "Hồ Chí Minh",
                            Country = "Việt Nam",
                            Email = "khachhang3@gmail.com",
                            Gender = 1,
                            Name = "Nguyễn Bá Hoàng",
                            Password = "khachhang3",
                            Phone = "0942400724",
                            Username = "khachhang3"
                        },
                        new
                        {
                            Id = 4,
                            Address = "167/19 Đặng Thùy Trâm",
                            Avata = "nhuy.png",
                            City = "Hồ Chí Minh",
                            Country = "Việt Nam",
                            Email = "khachhang4@gmail.com",
                            Gender = 1,
                            Name = "Nguyễn Văn Nhật Huy",
                            Password = "khachhang4",
                            Phone = "0942400725",
                            Username = "khachhang4"
                        });
                });

            modelBuilder.Entity("CoffeeBook.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Photo")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Discount");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiredDate = new DateTime(2021, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phiếu giảm giá 20k cho đơn hàng trên 100k",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/storage/852__C4_90o_CC_82_CC_80ng-gia_CC_81-29K_coupon.jpg",
                            Quantity = 10,
                            Value = 20000
                        },
                        new
                        {
                            Id = 2,
                            ExpiredDate = new DateTime(2021, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ưu đãi 30% (tối đa 35k) đơn từ 2 món bất kỳ",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/Coupondelivery30_684527.jpg",
                            Quantity = 10,
                            Value = 20000
                        },
                        new
                        {
                            Id = 3,
                            ExpiredDate = new DateTime(2021, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ưu đãi 20% đơn Pickup 2 món bất kỳ",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/storage/696_Coupon_20Pickup_2020_.jpg",
                            Quantity = 10,
                            Value = 20000
                        },
                        new
                        {
                            Id = 4,
                            ExpiredDate = new DateTime(2021, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ưu đãi 30% (tối đa 35k) đơn từ 2 món bất kỳ",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/Coupondelivery30_684527.jpg",
                            Quantity = 10,
                            Value = 20000
                        },
                        new
                        {
                            Id = 5,
                            ExpiredDate = new DateTime(2021, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ưu đãi 30% (tối đa 35k) đơn từ 2 món bất kỳ",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/storage/696_Coupon_20Pickup_2020_.jpg",
                            Quantity = 10,
                            Value = 20000
                        });
                });

            modelBuilder.Entity("CoffeeBook.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<long>("Salary")
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Hoạt động");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("StoreId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("CoffeeBook.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<long>("Salary")
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Hoạt động");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("CoffeeBook.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Bạn mua 5 ly cà phê - Nhà tặng thêm 2 (Hạn sử dụng 10 ngày kể từ ngày mua).",
                            Thumbnail = "https://feed.thecoffeehouse.com/content/images/2021/08/img_8668_grande.jpg",
                            Title = "Nghệ thuật pha chế - Cold Brew 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Bạn mua 5 ly cà phê - Nhà tặng thêm 2 (Hạn sử dụng 10 ngày kể từ ngày mua).",
                            Thumbnail = "https://feed.thecoffeehouse.com/content/images/2021/08/img_8668_grande.jpg",
                            Title = "Nghệ thuật pha chế - Espresso 1"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Bạn mua 5 ly cà phê - Nhà tặng thêm 2 (Hạn sử dụng 10 ngày kể từ ngày mua).",
                            Thumbnail = "https://feed.thecoffeehouse.com/content/images/2021/08/img_8668_grande.jpg",
                            Title = "Nghệ thuật pha chế - Cold Brew 2"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Bạn mua 5 ly cà phê - Nhà tặng thêm 2 (Hạn sử dụng 10 ngày kể từ ngày mua).",
                            Thumbnail = "https://feed.thecoffeehouse.com/content/images/2021/08/img_8668_grande.jpg",
                            Title = "Nghệ thuật pha chế - Espresso 2"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Bạn mua 5 ly cà phê - Nhà tặng thêm 2 (Hạn sử dụng 10 ngày kể từ ngày mua).",
                            Thumbnail = "https://feed.thecoffeehouse.com/content/images/2021/08/img_8668_grande.jpg",
                            Title = "Nghệ thuật pha chế - Cold Brew 3"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Bạn mua 5 ly cà phê - Nhà tặng thêm 2 (Hạn sử dụng 10 ngày kể từ ngày mua).",
                            Thumbnail = "https://feed.thecoffeehouse.com/content/images/2021/08/img_8668_grande.jpg",
                            Title = "Nghệ thuật pha chế - Espresso 3"
                        });
                });

            modelBuilder.Entity("CoffeeBook.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 714, DateTimeKind.Local).AddTicks(2755),
                            Description = "Cà phê được pha phin truyền thống kết hợp với sữa đặc tạo nên hương vị đậm đà, hài hòa giữa vị ngọt đầu lưỡi và vị đắng thanh thoát nơi hậu vị.",
                            Name = "Thùng 24 Lon Cà Phê Sữa Đá",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/24-lon-cpsd_225680_400x400.jpg",
                            Price = 336000,
                            ProductTypeId = 1,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2578),
                            Description = "Với thiết kế lon cao trẻ trung, hiện đại và tiện lợi, Cà phê sữa đá lon thơm ngon đậm vị của The Coffee House sẽ đồng hành cùng nhịp sống sôi nổi của tuổi trẻ và giúp bạn có được một ngày làm việc đầy hứng khởi.",
                            Name = "Cà Phê Sữa Đá Hòa Tan",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/cpsd-3in1_971575_400x400.jpg",
                            Price = 44000,
                            ProductTypeId = 1,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2630),
                            Description = "Được rang dưới nhiệt độ vàng, Cà phê Peak Flavor - Hương thơm đỉnh cao lưu giữ trọn vẹn hương thơm tinh tế đặc trưng của cà phê Robusta Đăk Nông và Arabica Cầu Đất. Với sự hòa trộn nhiều cung bậc giữa hương và vị sẽ mang đến cho bạn một ngày mới tràn đầy cảm hứng.",
                            Name = "Cà Phê Peak Flavor Hương Thơm Đỉnh Cao (350G)",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/peak-plavor-nopromo_715372_400x400.jpg",
                            Price = 90000,
                            ProductTypeId = 1,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2634),
                            Description = "Cà phê được pha phin truyền thống kết hợp với sữa đặc tạo nên hương vị đậm đà, hài hòa giữa vị ngọt đầu lưỡi và vị đắng thanh thoát nơi hậu vị.",
                            Name = "Cà Phê Sữa Đá",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/rich-finish-nopromo_485968.jpg",
                            Price = 90000,
                            ProductTypeId = 1,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2636),
                            Description = "Bạc sỉu chính là 'Ly sữa trắng kèm một chút cà phê'. Thức uống này rất phù hợp những ai vừa muốn trải nghiệm chút vị đắng của cà phê vừa muốn thưởng thức vị ngọt béo ngậy từ sữa.",
                            Name = "Bạc Sỉu",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/caphe-suada--bacsiu_063797_400x400.jpg",
                            Price = 32000,
                            ProductTypeId = 2,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2637),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Caramel Macchiato Đá",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/caramel-macchiato_143623_400x400.jpg",
                            Price = 50000,
                            ProductTypeId = 2,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2640),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Cà Phê Đá Xay-Lạnh",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/cf-da-xay-(1)_158038_400x400.jpg",
                            Price = 59000,
                            ProductTypeId = 2,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2641),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Trà sữa Oolong Nướng Trân Châu",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/olong-nuong-tran-chau_017573_400x400.jpg",
                            Price = 55000,
                            ProductTypeId = 3,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2643),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Hồng Trà Sữa Trân Châu",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/tra-nhan-da_484810_400x400.jpg",
                            Price = 55000,
                            ProductTypeId = 3,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2645),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Hồng Trà Latte Macchiato",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/hong-tra-latte_618293_400x400.jpg",
                            Price = 55000,
                            ProductTypeId = 3,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2647),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Trà Long Nhãn Hạt Chia",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/tra-nhan-da_484810_400x400.jpg",
                            Price = 45000,
                            ProductTypeId = 3,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2649),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Cà Phê Đá Xay-Lạnh",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/cf-da-xay-(1)_158038_400x400.jpg",
                            Price = 59000,
                            ProductTypeId = 4,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2651),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Cookie Đá Xay",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/Chocolate-ice-blended_183602_400x400.jpg",
                            Price = 59000,
                            ProductTypeId = 4,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2652),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Sinh Tố Việt Quất",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/sinh-to-viet-quoc_145138_400x400.jpg",
                            Price = 59000,
                            ProductTypeId = 4,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2654),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Chocolate Đá Xay",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/Chocolate-ice-blended_400940_400x400.jpg",
                            Price = 59000,
                            ProductTypeId = 4,
                            Size = 0,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2656),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Mochi Kem Việt Quất",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/mochi-vietqwuoc_130861_400x400.jpg",
                            Price = 19000,
                            ProductTypeId = 5,
                            Size = 0,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2657),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Mochi Kem Phúc Bồn Tử",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/mochi-phucbontu_097500_400x400.jpg",
                            Price = 19000,
                            ProductTypeId = 5,
                            Size = 0,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2659),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Mochi Kem Dừa Dứa",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/mochi-dua_975992_400x400.jpg",
                            Price = 19000,
                            ProductTypeId = 5,
                            Size = 0,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2021, 11, 18, 23, 26, 36, 715, DateTimeKind.Local).AddTicks(2661),
                            Description = "Caramel Macchiato sẽ mang đến một sự ngạc nhiên thú vị khi vị thơm béo của bọt sữa, sữa tươi, vị đắng thanh thoát của cà phê Espresso hảo hạng và vị ngọt đậm của sốt caramel được gói gọn trong một tách cà phê.",
                            Name = "Mochi Kem Xoài",
                            Photo = "https://minio.thecoffeehouse.com/image/admin/mochi-xoai_355815_400x400.jpg",
                            Price = 19000,
                            ProductTypeId = 5,
                            Size = 0,
                            SupplierId = 2
                        });
                });

            modelBuilder.Entity("CoffeeBook.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cà phê đóng gói",
                            Name = "Cà phê gói - Uống liền"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cà phê pha",
                            Name = "Cà phê pha"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Trà Trái Cây - Trà sữa",
                            Name = "Trà Trái Cây - Trà sữa"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Đá xay",
                            Name = "Đá xay - Choco - Matcha"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bánh",
                            Name = "Bánh - snack"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Đồ lưu niệm",
                            Name = "Bộ sưu tập - quà tặng"
                        });
                });

            modelBuilder.Entity("CoffeeBook.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator",
                            RoleName = "admin"
                        });
                });

            modelBuilder.Entity("CoffeeBook.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ShoppingCart");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4
                        });
                });

            modelBuilder.Entity("CoffeeBook.Models.ShoppingCart_Product", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCart_Product");

                    b.HasData(
                        new
                        {
                            ShoppingCartId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            ShoppingCartId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            ShoppingCartId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            ShoppingCartId = 2,
                            ProductId = 3
                        },
                        new
                        {
                            ShoppingCartId = 3,
                            ProductId = 3
                        },
                        new
                        {
                            ShoppingCartId = 3,
                            ProductId = 2
                        },
                        new
                        {
                            ShoppingCartId = 4,
                            ProductId = 1
                        },
                        new
                        {
                            ShoppingCartId = 4,
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("CoffeeBook.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("ManagerId")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Store");
                });

            modelBuilder.Entity("CoffeeBook.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Supplier");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Quận 1",
                            City = "Hồ Chí Minh",
                            Country = "Việt Nam",
                            Description = "Chuyên phân phối nguyên liệu, sản phầm đồ uống",
                            Name = "Nhà phân phối sản phẩm đồ uống",
                            Phone = "01122334455",
                            Url = "supplier1.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Quận 1",
                            City = "Hồ Chí Minh",
                            Country = "Việt Nam",
                            Description = "Chuyên phân phối nguyên liệu, sản phầm đồ ăn",
                            Name = "Nhà phân phối sản phẩm đồ ăn",
                            Phone = "11122334455",
                            Url = "supplier2.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Quận 1",
                            City = "Hồ Chí Minh",
                            Country = "Việt Nam",
                            Description = "Chuyên phân phối đồ sưu tập, quà lưu niệm",
                            Name = "Nhà phân phối đồ sưu tập, quà lưu niệm",
                            Phone = "21122334455",
                            Url = "supplier3.com"
                        });
                });

            modelBuilder.Entity("CoffeeBook.Models.Account", b =>
                {
                    b.HasOne("CoffeeBook.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CoffeeBook.Models.Bill", b =>
                {
                    b.HasOne("CoffeeBook.Models.Customer", "Customer")
                        .WithMany("Bills")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CoffeeBook.Models.Employee", b =>
                {
                    b.HasOne("CoffeeBook.Models.Store", "Store")
                        .WithMany("Employees")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CoffeeBook.Models.Product", b =>
                {
                    b.HasOne("CoffeeBook.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeBook.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CoffeeBook.Models.ShoppingCart", b =>
                {
                    b.HasOne("CoffeeBook.Models.Customer", "Customer")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CoffeeBook.Models.ShoppingCart_Product", b =>
                {
                    b.HasOne("CoffeeBook.Models.Product", "Product")
                        .WithMany("ShoppingCart_Products")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeBook.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("ShoppingCart_Products")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("CoffeeBook.Models.Store", b =>
                {
                    b.HasOne("CoffeeBook.Models.Manager", "Manager")
                        .WithOne("Store")
                        .HasForeignKey("CoffeeBook.Models.Store", "ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("CoffeeBook.Models.Customer", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("ShoppingCarts");
                });

            modelBuilder.Entity("CoffeeBook.Models.Manager", b =>
                {
                    b.Navigation("Store");
                });

            modelBuilder.Entity("CoffeeBook.Models.Product", b =>
                {
                    b.Navigation("ShoppingCart_Products");
                });

            modelBuilder.Entity("CoffeeBook.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CoffeeBook.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CoffeeBook.Models.ShoppingCart", b =>
                {
                    b.Navigation("ShoppingCart_Products");
                });

            modelBuilder.Entity("CoffeeBook.Models.Store", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CoffeeBook.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
